/**
 * @file http_server.c
 * @brief HTTPS web server implementation
 */

#include "http_server.h"
#include "esp_log.h"

static const char *TAG = "HTTP_SERVER";

#ifndef CONFIG_IDF_TARGET_ESP32C6
// Full HTTP server implementation for ESP32-S3

#include "services/core/services.h"
#include "services/core/services_provisioning_bridge.h"
#include "provisioning/provisioning_runner.h"
#include "services/time_sync/time_sync.h"
#include "services/logging/log_history.h"
#include "storage/sd_logger.h"
#include "services/keys/api_key_manager.h"
#include "web_file_editor.h"
#include "services/telemetry/mqtt_telemetry.h"
#include "services/telemetry/mqtt_connection_controller.h"
#include "services/telemetry/mqtt_connection_watchdog.h"
#include "http_websocket.h"
#include "http_handlers_sensors.h"
#include "esp_https_server.h"
#include "esp_heap_caps.h"
#include "esp_timer.h"
#include "esp_wifi.h"
#include "esp_netif.h"
#include "esp_netif_ip_addr.h"
#include "esp_ota_ops.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "cJSON.h"
#include "nvs_flash.h"
#include "nvs.h"
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <dirent.h>
#include <errno.h>

static httpd_handle_t s_server = NULL;
static http_server_config_t s_http_config = {0};
static char *s_https_certificate = NULL;
static size_t s_https_certificate_len = 0;
static char *s_https_private_key = NULL;
static size_t s_https_private_key_len = 0;

static void http_server_free_tls_assets(void)
{
    if (s_https_certificate != NULL) {
        free(s_https_certificate);
        s_https_certificate = NULL;
        s_https_certificate_len = 0;
    }
    if (s_https_private_key != NULL) {
        free(s_https_private_key);
        s_https_private_key = NULL;
        s_https_private_key_len = 0;
    }
}


#define OTA_UPLOAD_BUFFER_SIZE 4096
#define LOG_API_MAX_ENTRIES     200
#define LOG_API_DEFAULT_LIMIT   50
#define LOG_API_MIN_LIMIT       1
#define LOG_DOWNLOAD_CHUNK_SIZE 2048

// External sensor reading functions from mqtt_telemetry.c
extern float read_temperature(void);
extern float read_humidity(void);
extern float read_soil_moisture(void);
extern float read_light_level(void);
extern float read_battery_level(void);

// Sensor manager functions
#include "sensors/sensor_manager.h"
#include "sensors/drivers/ezo_sensor.h"
#include "sensors/drivers/max17048.h"
#include "sensors/pipeline.h"
#include "services/telemetry/mqtt_telemetry.h"  // For MAX_SENSOR_VALUES

// Declare embedded web files (generated by CMake)
extern const uint8_t index_html_start[] asm("_binary_index_html_start");
extern const uint8_t index_html_end[]   asm("_binary_index_html_end");

static cJSON *create_sensors_object_from_cache(const sensor_cache_t *cache);
static const char *mqtt_state_to_string(mqtt_state_t state);
static const char *log_category_to_string(log_history_category_t category);
static esp_err_t api_logs_handler_live(httpd_req_t *req, int limit, int offset);
#if CONFIG_KC_SD_LOGGER_ENABLED
static bool api_logs_build_sd_path(const char *date_str, char *path, size_t path_len);
static esp_err_t api_logs_handler_sd(httpd_req_t *req, const char *date_str, int limit, int offset);
static esp_err_t api_logs_download_handler(httpd_req_t *req);
#endif
static esp_err_t api_logs_handler(httpd_req_t *req);

static cJSON *create_sensors_object_from_cache(const sensor_cache_t *cache)
{
    cJSON *sensors = cJSON_CreateObject();
    if (sensors == NULL || cache == NULL) {
        return sensors;
    }

    for (uint8_t i = 0; i < cache->sensor_count && i < 8; i++) {
        const cached_sensor_t *sensor = &cache->sensors[i];
        if (!sensor->valid) {
            continue;
        }

        if (sensor->value_count == 1) {
            cJSON_AddNumberToObject(sensors, sensor->sensor_type, sensor->values[0]);
        } else if (sensor->value_count > 1) {
            cJSON *sensor_obj = cJSON_CreateObject();
            if (sensor_obj == NULL) {
                continue;
            }

            if (strcmp(sensor->sensor_type, "HUM") == 0) {
                if (sensor->value_count >= 1) cJSON_AddNumberToObject(sensor_obj, "humidity", sensor->values[0]);
                if (sensor->value_count >= 2) cJSON_AddNumberToObject(sensor_obj, "air_temp", sensor->values[1]);
                if (sensor->value_count >= 3) cJSON_AddNumberToObject(sensor_obj, "dew_point", sensor->values[2]);
            } else if (strcmp(sensor->sensor_type, "EC") == 0) {
                if (sensor->value_count >= 1) cJSON_AddNumberToObject(sensor_obj, "conductivity", sensor->values[0]);
                if (sensor->value_count >= 2) cJSON_AddNumberToObject(sensor_obj, "tds", sensor->values[1]);
                if (sensor->value_count >= 3) cJSON_AddNumberToObject(sensor_obj, "salinity", sensor->values[2]);
                if (sensor->value_count >= 4) cJSON_AddNumberToObject(sensor_obj, "specific_gravity", sensor->values[3]);
            } else if (strcmp(sensor->sensor_type, "DO") == 0) {
                if (sensor->value_count >= 1) cJSON_AddNumberToObject(sensor_obj, "dissolved_oxygen", sensor->values[0]);
                if (sensor->value_count >= 2) cJSON_AddNumberToObject(sensor_obj, "saturation", sensor->values[1]);
            } else {
                for (uint8_t j = 0; j < sensor->value_count; j++) {
                    char field_name[16];
                    snprintf(field_name, sizeof(field_name), "value_%d", j);
                    cJSON_AddNumberToObject(sensor_obj, field_name, sensor->values[j]);
                }
            }

            cJSON_AddItemToObject(sensors, sensor->sensor_type, sensor_obj);
        }
    }

    return sensors;
}

static const char *mqtt_state_to_string(mqtt_state_t state)
{
    switch (state) {
        case MQTT_STATE_DISCONNECTED:
            return "disconnected";
        case MQTT_STATE_CONNECTING:
            return "connecting";
        case MQTT_STATE_CONNECTED:
            return "connected";
        case MQTT_STATE_ERROR:
            return "error";
        default:
            return "unknown";
    }
}

static esp_err_t api_logs_handler_live(httpd_req_t *req, int limit, int offset)
{
    const size_t buffer_size = LOG_API_MAX_ENTRIES * sizeof(log_history_entry_t);
    log_history_entry_t *entries = heap_caps_malloc(buffer_size, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (entries == NULL) {
        entries = malloc(buffer_size);
    }
    if (entries == NULL) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }
    memset(entries, 0, buffer_size);

    size_t total_entries = log_history_get_entries(LOG_HISTORY_FILTER_ALL, LOG_API_MAX_ENTRIES, entries);
    size_t skip_newest = offset >= 0 ? (size_t)offset : 0;
    if (skip_newest > total_entries) {
        skip_newest = total_entries;
    }
    size_t available = total_entries - skip_newest;
    size_t desired = available < (size_t)limit ? available : (size_t)limit;
    size_t start = (available > desired) ? (available - desired) : 0;
    size_t end = start + desired;
    size_t returned = desired;
    bool has_more = (skip_newest + returned) < total_entries;

    cJSON *root = cJSON_CreateObject();
    cJSON *items = cJSON_CreateArray();
    if (root == NULL || items == NULL) {
        if (root != NULL) {
            cJSON_Delete(root);
        }
        if (items != NULL) {
            cJSON_Delete(items);
        }
        free(entries);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    const int64_t now_us = esp_timer_get_time();
    for (size_t i = start; i < end; ++i) {
        const log_history_entry_t *entry = &entries[i];
        cJSON *item = cJSON_CreateObject();
        if (item == NULL) {
            continue;
        }
        cJSON_AddNumberToObject(item, "sequence", entry->sequence);
        cJSON_AddStringToObject(item, "level", log_category_to_string(entry->category));
        cJSON_AddStringToObject(item, "tag", entry->tag);
        cJSON_AddStringToObject(item, "message", entry->message);
        cJSON_AddNumberToObject(item, "timestamp_us", (double)entry->timestamp_us);
        double age_sec = (double)(now_us - entry->timestamp_us) / 1000000.0;
        if (age_sec < 0) {
            age_sec = 0;
        }
        cJSON_AddNumberToObject(item, "age_sec", age_sec);
        cJSON_AddItemToArray(items, item);
    }

    cJSON_AddItemToObject(root, "entries", items);
    cJSON_AddNumberToObject(root, "count", returned);
    cJSON_AddNumberToObject(root, "total", total_entries);
    cJSON_AddNumberToObject(root, "limit", limit);
    cJSON_AddNumberToObject(root, "offset", offset);
    cJSON_AddBoolToObject(root, "has_more", has_more);
    cJSON_AddStringToObject(root, "source", "live");

    char *json = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (json == NULL) {
        free(entries);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json, HTTPD_RESP_USE_STRLEN);
    free(json);
    free(entries);
    return ESP_OK;
}

#if CONFIG_KC_SD_LOGGER_ENABLED
static bool api_logs_build_sd_path(const char *date_str, char *path, size_t path_len)
{
    if (date_str == NULL || path == NULL || path_len == 0) {
        return false;
    }
    int year = 0, month = 0, day = 0;
    if (sscanf(date_str, "%4d-%2d-%2d", &year, &month, &day) != 3) {
        return false;
    }
    if (year < 2000 || month < 1 || month > 12 || day < 1 || day > 31) {
        return false;
    }
    int written = snprintf(path,
                           path_len,
                           SD_LOGGER_LOG_DIR "/%04d%02d%02d.log",
                           year,
                           month,
                           day);
    return written > 0 && written < (int)path_len;
}

static esp_err_t api_logs_handler_sd(httpd_req_t *req, const char *date_str, int limit, int offset)
{
    char path[128];
    if (!api_logs_build_sd_path(date_str, path, sizeof(path))) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid date");
        return ESP_ERR_INVALID_ARG;
    }

    FILE *file = fopen(path, "r");
    if (file == NULL) {
        httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Log file not found");
        return ESP_ERR_NOT_FOUND;
    }

    if (limit < LOG_API_MIN_LIMIT) {
        limit = LOG_API_MIN_LIMIT;
    }
    if (limit > LOG_API_MAX_ENTRIES) {
        limit = LOG_API_MAX_ENTRIES;
    }
    if (offset < 0) {
        offset = 0;
    }

    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to inspect log file");
        return ESP_FAIL;
    }
    long file_size = ftell(file);
    if (file_size < 0) {
        fclose(file);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to inspect log file");
        return ESP_FAIL;
    }

    size_t lines_needed = (size_t)offset + (size_t)limit;
    if (lines_needed == 0) {
        lines_needed = (size_t)limit;
    }
    if (lines_needed == 0) {
        lines_needed = LOG_API_DEFAULT_LIMIT;
    }

    long tail_offset = 0;
    bool has_more = false;

    if (file_size > 0 && lines_needed > 0) {
        const size_t block_size = 4096;
        char *block = malloc(block_size);
        if (block == NULL) {
            fclose(file);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
            return ESP_ERR_NO_MEM;
        }

        long scan_pos = file_size;
        size_t newline_count = 0;
        bool offset_found = false;

        while (scan_pos > 0 && newline_count < lines_needed) {
            size_t chunk = (scan_pos >= (long)block_size) ? block_size : (size_t)scan_pos;
            scan_pos -= chunk;
            if (fseek(file, scan_pos, SEEK_SET) != 0) {
                free(block);
                fclose(file);
                httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Seek failed");
                return ESP_FAIL;
            }
            size_t read_bytes = fread(block, 1, chunk, file);
            for (int i = (int)read_bytes - 1; i >= 0; --i) {
                if (block[i] == '\n') {
                    newline_count++;
                    if (newline_count == lines_needed) {
                        tail_offset = scan_pos + i + 1;
                        offset_found = true;
                        break;
                    }
                }
            }
            if (offset_found) {
                break;
            }
        }

        if (!offset_found) {
            tail_offset = 0;
        } else if (tail_offset > 0) {
            has_more = true;
        }

        free(block);
    }

    if (fseek(file, tail_offset, SEEK_SET) != 0) {
        fclose(file);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Seek failed");
        return ESP_FAIL;
    }

    size_t window_capacity = (size_t)offset + (size_t)limit;
    if (window_capacity == 0) {
        window_capacity = (size_t)limit;
    }
    if (window_capacity == 0) {
        window_capacity = LOG_API_DEFAULT_LIMIT;
    }

    cJSON **parsed_entries = calloc(window_capacity, sizeof(cJSON *));
    if (parsed_entries == NULL) {
        fclose(file);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    char line[768];
    size_t parsed_count = 0;
    size_t parse_errors = 0;
    while (parsed_count < window_capacity && fgets(line, sizeof(line), file) != NULL) {
        size_t len = strlen(line);
        while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) {
            line[--len] = '\0';
        }
        if (len == 0) {
            continue;
        }
        cJSON *item = cJSON_Parse(line);
        if (item == NULL) {
            if (parse_errors < 5) {
                ESP_LOGW(TAG, "Failed to parse SD log line: %.64s", line);
            }
            parse_errors++;
            continue;
        }
        parsed_entries[parsed_count++] = item;
    }

    fclose(file);

    cJSON *root = cJSON_CreateObject();
    cJSON *items = cJSON_CreateArray();
    if (root == NULL || items == NULL) {
        for (size_t i = 0; i < parsed_count; ++i) {
            if (parsed_entries[i] != NULL) {
                cJSON_Delete(parsed_entries[i]);
            }
        }
        free(parsed_entries);
        if (root != NULL) {
            cJSON_Delete(root);
        }
        if (items != NULL) {
            cJSON_Delete(items);
        }
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    size_t end_idx = (parsed_count > (size_t)offset) ? (parsed_count - (size_t)offset) : 0;
    size_t start_idx = (end_idx > (size_t)limit) ? (end_idx - (size_t)limit) : 0;
    size_t returned = 0;

    for (size_t i = start_idx; i < end_idx; ++i) {
        cJSON *entry = parsed_entries[i];
        if (entry == NULL) {
            continue;
        }
        cJSON_AddItemToArray(items, entry);
        parsed_entries[i] = NULL;
        returned++;
    }

    for (size_t i = 0; i < parsed_count; ++i) {
        if (parsed_entries[i] != NULL) {
            cJSON_Delete(parsed_entries[i]);
        }
    }
    free(parsed_entries);

    size_t total_entries = (tail_offset == 0) ? parsed_count : 0;

    cJSON_AddItemToObject(root, "entries", items);
    cJSON_AddNumberToObject(root, "count", returned);
    cJSON_AddNumberToObject(root, "total", total_entries);
    cJSON_AddNumberToObject(root, "limit", limit);
    cJSON_AddNumberToObject(root, "offset", offset);
    cJSON_AddBoolToObject(root, "has_more", has_more);
    cJSON_AddStringToObject(root, "source", "sd");
    cJSON_AddStringToObject(root, "date", date_str);
    ESP_LOGI(TAG,
             "SD logs %s returning %u entries (offset=%d limit=%d has_more=%d parse_errors=%u)",
             date_str,
             (unsigned)returned,
             offset,
             limit,
             has_more,
             (unsigned)parse_errors);

    char *json = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (json == NULL) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json, HTTPD_RESP_USE_STRLEN);
    free(json);
    return ESP_OK;
}

static esp_err_t api_logs_download_handler(httpd_req_t *req)
{
    char query[64] = {0};
    char date_param[16] = {0};

    int query_len = httpd_req_get_url_query_len(req);
    if (query_len <= 0 || query_len >= (int)sizeof(query)) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Missing date");
        return ESP_ERR_INVALID_ARG;
    }
    if (httpd_req_get_url_query_str(req, query, sizeof(query)) != ESP_OK ||
        httpd_query_key_value(query, "date", date_param, sizeof(date_param)) != ESP_OK ||
        date_param[0] == '\0') {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Missing date");
        return ESP_ERR_INVALID_ARG;
    }

    char path[128];
    if (!api_logs_build_sd_path(date_param, path, sizeof(path))) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid date");
        return ESP_ERR_INVALID_ARG;
    }

    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Log file not found");
        return ESP_ERR_NOT_FOUND;
    }

    char filename[32];
    snprintf(filename, sizeof(filename), "%s.log", date_param);
    char disposition[80];
    snprintf(disposition, sizeof(disposition), "attachment; filename=\"%s\"", filename);

    httpd_resp_set_type(req, "application/x-ndjson");
    httpd_resp_set_hdr(req, "Content-Disposition", disposition);
    httpd_resp_set_hdr(req, "Cache-Control", "no-store, no-cache, must-revalidate");

    char *chunk = malloc(LOG_DOWNLOAD_CHUNK_SIZE);
    if (chunk == NULL) {
        fclose(file);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    esp_err_t send_res = ESP_OK;
    size_t bytes_read = 0;
    while ((bytes_read = fread(chunk, 1, LOG_DOWNLOAD_CHUNK_SIZE, file)) > 0) {
        send_res = httpd_resp_send_chunk(req, chunk, bytes_read);
        if (send_res != ESP_OK) {
            break;
        }
    }

    bool read_error = ferror(file);
    free(chunk);
    fclose(file);

    if (send_res != ESP_OK) {
        httpd_resp_sendstr_chunk(req, NULL);
        return send_res;
    }

    esp_err_t finish_res = httpd_resp_sendstr_chunk(req, NULL);
    if (finish_res != ESP_OK) {
        return finish_res;
    }

    if (read_error) {
        ESP_LOGW(TAG, "SD log %s truncated due to read error", date_param);
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "SD log %s streamed to client", date_param);
    return ESP_OK;
}
#endif

static const char *log_category_to_string(log_history_category_t category)
{
    switch (category) {
        case LOG_HISTORY_CATEGORY_ERROR:
            return "ERROR";
        case LOG_HISTORY_CATEGORY_WARNING:
            return "WARNING";
        case LOG_HISTORY_CATEGORY_SENSOR:
            return "SENSOR";
        default:
            return "INFO";
    }
}

static bool http_sample_cpu_usage(float *out_percent)
{
    if (out_percent == NULL) {
        return false;
    }

#if CONFIG_FREERTOS_USE_TRACE_FACILITY && CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS
    const UBaseType_t task_count = uxTaskGetNumberOfTasks();
    if (task_count == 0) {
        return false;
    }

    TaskStatus_t *status_array = calloc(task_count, sizeof(TaskStatus_t));
    if (status_array == NULL) {
        return false;
    }

    uint32_t total_run_time = 0;
    const UBaseType_t captured = uxTaskGetSystemState(status_array, task_count, &total_run_time);
    if (captured == 0 || total_run_time == 0) {
        free(status_array);
        return false;
    }

#if CONFIG_FREERTOS_UNICORE
    TaskHandle_t idle_handles[1] = {xTaskGetIdleTaskHandle()};
    const int idle_count = 1;
#else
    TaskHandle_t idle_handles[portNUM_PROCESSORS] = {0};
    for (int core = 0; core < portNUM_PROCESSORS; ++core) {
        idle_handles[core] = xTaskGetIdleTaskHandleForCore(core);
    }
    const int idle_count = portNUM_PROCESSORS;
#endif

    uint32_t idle_run_time = 0;
    for (UBaseType_t i = 0; i < captured; ++i) {
        for (int cpu = 0; cpu < idle_count; ++cpu) {
            if (status_array[i].xHandle == idle_handles[cpu]) {
                idle_run_time += status_array[i].ulRunTimeCounter;
            }
        }
    }

    free(status_array);

    static uint32_t s_prev_total_runtime = 0;
    static uint32_t s_prev_idle_runtime = 0;
    if (s_prev_total_runtime == 0) {
        s_prev_total_runtime = total_run_time;
        s_prev_idle_runtime = idle_run_time;
        return false;
    }

    const uint32_t delta_total = total_run_time - s_prev_total_runtime;
    const uint32_t delta_idle = idle_run_time - s_prev_idle_runtime;

    s_prev_total_runtime = total_run_time;
    s_prev_idle_runtime = idle_run_time;

    if (delta_total == 0 || delta_idle > delta_total) {
        return false;
    }

    float usage = 100.0f * (1.0f - ((float)delta_idle / (float)delta_total));
    if (usage < 0.0f) {
        usage = 0.0f;
    } else if (usage > 100.0f) {
        usage = 100.0f;
    }

    *out_percent = usage;
    return true;
#else
    return false;
#endif
}

/**
 * @brief Favicon handler - return 204 No Content to avoid 404 errors
 */
static esp_err_t favicon_handler(httpd_req_t *req)
{
    httpd_resp_set_status(req, "204 No Content");
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

/**
 * @brief Root handler - serve dashboard from on-device filesystem or embedded fallback
 */
static esp_err_t root_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Connection", "keep-alive");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache, no-store, must-revalidate");
    httpd_resp_set_hdr(req, "Pragma", "no-cache");
    httpd_resp_set_hdr(req, "Expires", "0");
    
    // Try to load from the writable filesystem first
    char *content = NULL;
    size_t size = 0;
    if (web_editor_load_file("index.html", &content, &size) == ESP_OK) {
        ESP_LOGI(TAG, "Serving index.html from FATFS (%d bytes)", size);
        httpd_resp_send(req, content, size);
        free(content);
        return ESP_OK;
    }
    
    // Fallback to embedded HTML
    ESP_LOGI(TAG, "Serving index.html from embedded image (filesystem read failed)");
    const size_t html_size = index_html_end - index_html_start;
    httpd_resp_send(req, (const char *)index_html_start, html_size);
    return ESP_OK;
}

/**
 * @brief API status endpoint - return device status as JSON
 */
static esp_err_t api_status_handler(httpd_req_t *req)
{
    cJSON *root = cJSON_CreateObject();
    
    // Device ID
    char device_id[SERVICES_DEVICE_ID_MAX_LEN] = {0};
    if (services_provisioning_load_device_id(device_id, sizeof(device_id)) == ESP_OK &&
        device_id[0] != '\0') {
        cJSON_AddStringToObject(root, "device_id", device_id);
    } else {
        cJSON_AddStringToObject(root, "device_id", "unknown");
    }
    
    // WiFi SSID
    provisioning_saved_network_info_t saved_network = {0};
    if (provisioning_get_saved_network(&saved_network) == ESP_OK && saved_network.has_credentials) {
        cJSON_AddStringToObject(root, "wifi_ssid", saved_network.ssid);
    } else {
        cJSON_AddStringToObject(root, "wifi_ssid", "Not configured");
    }
    
    // IP Address
    if (provisioning_wifi_is_connected()) {
        char ip_str[16] = "Connected";
        esp_netif_t *sta_netif = esp_netif_get_handle_from_ifkey("WIFI_STA_DEF");
        if (sta_netif != NULL) {
            esp_netif_ip_info_t ip_info = {0};
            if (esp_netif_get_ip_info(sta_netif, &ip_info) == ESP_OK) {
                snprintf(ip_str, sizeof(ip_str), IPSTR, IP2STR(&ip_info.ip));
            }
        }
        cJSON_AddStringToObject(root, "ip_address", ip_str);
    } else {
        cJSON_AddStringToObject(root, "ip_address", "Disconnected");
    }
    
    // WiFi RSSI
    if (provisioning_wifi_is_connected()) {
        wifi_ap_record_t ap_info;
        if (esp_wifi_sta_get_ap_info(&ap_info) == ESP_OK) {
            cJSON_AddNumberToObject(root, "rssi", ap_info.rssi);
        }
    }
    
    // Uptime
    cJSON_AddNumberToObject(root, "uptime", esp_timer_get_time() / 1000000);
    
    // Current time
    char time_str[64];
    if (time_sync_get_time_string(time_str, sizeof(time_str), NULL) == ESP_OK) {
        cJSON_AddStringToObject(root, "current_time", time_str);
    } else {
        cJSON_AddStringToObject(root, "current_time", "Not synced");
    }
    
    // Free heap
    cJSON_AddNumberToObject(root, "free_heap", esp_get_free_heap_size());
    
    // CPU usage (derived from FreeRTOS run-time stats)
    float cpu_usage = 0.0f;
    if (http_sample_cpu_usage(&cpu_usage)) {
        cJSON_AddNumberToObject(root, "cpu_usage", cpu_usage);
    } else {
        cJSON_AddNumberToObject(root, "cpu_usage", -1);
    }
    
    sensor_pipeline_snapshot_t snapshot = {0};
    if (sensor_pipeline_snapshot(NULL, &snapshot) == ESP_OK) {
        cJSON_AddBoolToObject(root, "sensors_ready", snapshot.readiness.sensors_ready);
        cJSON_AddBoolToObject(root, "sensor_task_launched", snapshot.readiness.sensor_task_launched);
        cJSON_AddNumberToObject(root, "sensor_interval_sec", snapshot.reading_interval_sec);

        if (snapshot.cache_valid) {
            const sensor_cache_t *cache = &snapshot.cache;
            if (cache->battery_valid) {
                cJSON_AddNumberToObject(root, "battery", cache->battery_percentage);
            }

            cJSON *sensors = create_sensors_object_from_cache(cache);
            if (sensors != NULL) {
                cJSON_AddItemToObject(root, "sensors", sensors);
            }
        }
    }
    
    // Send JSON response
    const char *json_str = cJSON_PrintUnformatted(root);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, HTTPD_RESP_USE_STRLEN);
    
    free((void *)json_str);
    cJSON_Delete(root);
    return ESP_OK;
}

static esp_err_t api_logs_handler(httpd_req_t *req)
{
    char query[128] = {0};
    char source_param[16] = {0};
    char date_param[16] = {0};
    char limit_param[12] = {0};
    char offset_param[12] = {0};

    int limit = LOG_API_DEFAULT_LIMIT;
    int offset = 0;

    int query_len = httpd_req_get_url_query_len(req);
    if (query_len > 0 && query_len < (int)sizeof(query)) {
        if (httpd_req_get_url_query_str(req, query, sizeof(query)) == ESP_OK) {
            httpd_query_key_value(query, "source", source_param, sizeof(source_param));
            httpd_query_key_value(query, "date", date_param, sizeof(date_param));
            httpd_query_key_value(query, "limit", limit_param, sizeof(limit_param));
            httpd_query_key_value(query, "offset", offset_param, sizeof(offset_param));
        }
    }

    if (limit_param[0] != '\0') {
        char *end = NULL;
        long value = strtol(limit_param, &end, 10);
        if (end != limit_param) {
            if (value < LOG_API_MIN_LIMIT) {
                value = LOG_API_MIN_LIMIT;
            }
            if (value > LOG_API_MAX_ENTRIES) {
                value = LOG_API_MAX_ENTRIES;
            }
            limit = (int)value;
        }
    }

    if (offset_param[0] != '\0') {
        char *end = NULL;
        long value = strtol(offset_param, &end, 10);
        if (end != offset_param) {
            if (value < 0) {
                value = 0;
            }
            offset = (int)value;
        }
    }

    const bool use_sd_source = strcasecmp(source_param, "sd") == 0;
    if (use_sd_source) {
#if CONFIG_KC_SD_LOGGER_ENABLED
        if (date_param[0] == '\0') {
            httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Missing date");
            return ESP_ERR_INVALID_ARG;
        }
        return api_logs_handler_sd(req, date_param, limit, offset);
#else
        httpd_resp_send_err(req, HTTPD_501_NOT_IMPLEMENTED, "SD logging disabled");
        return ESP_ERR_NOT_SUPPORTED;
#endif
    }

    return api_logs_handler_live(req, limit, offset);
}

static esp_err_t api_mqtt_status_handler(httpd_req_t *req)
{
    mqtt_connection_metrics_t metrics = {0};
    mqtt_connection_controller_get_metrics(&metrics);

    cJSON *root = cJSON_CreateObject();
    if (root == NULL) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_ERR_NO_MEM;
    }

    const int64_t now_us = esp_timer_get_time();
    mqtt_telemetry_diagnostics_t telemetry_diag = {0};
    mqtt_telemetry_get_diagnostics(&telemetry_diag);
    mqtt_watchdog_metrics_t watchdog_metrics = {0};
    mqtt_connection_watchdog_get_metrics(&watchdog_metrics);

    const char *state_str = mqtt_state_to_string(metrics.state);
    cJSON_AddStringToObject(root, "state", state_str);
    cJSON_AddNumberToObject(root, "state_code", metrics.state);
    cJSON_AddBoolToObject(root, "should_run", metrics.should_run);
    cJSON_AddBoolToObject(root, "client_running", metrics.client_running);
    cJSON_AddBoolToObject(root, "supervisor_running", metrics.supervisor_running);
    cJSON_AddBoolToObject(root, "connected", metrics.state == MQTT_STATE_CONNECTED);
    cJSON_AddNumberToObject(root, "reconnect_count", metrics.reconnect_count);
    cJSON_AddNumberToObject(root, "consecutive_failures", metrics.consecutive_failures);
    cJSON_AddNumberToObject(root, "last_transition_us", (double)metrics.last_transition_us);

    if (metrics.last_transition_us > 0) {
        int64_t delta_us = now_us - metrics.last_transition_us;
        if (delta_us < 0) {
            delta_us = 0;
        }
        double delta_sec = (double)delta_us / 1000000.0;
        cJSON_AddNumberToObject(root, "seconds_since_transition", delta_sec);
    } else {
        cJSON_AddNumberToObject(root, "seconds_since_transition", -1);
    }

    const telemetry_pipeline_metrics_t *pipeline_metrics = &telemetry_diag.pipeline_metrics;
    cJSON *telemetry = cJSON_CreateObject();
    if (telemetry != NULL) {
        cJSON_AddNumberToObject(telemetry, "publish_interval_sec", telemetry_diag.publish_interval_sec);
        cJSON_AddNumberToObject(telemetry, "busy_backoff_ms", telemetry_diag.busy_backoff_ms);
        cJSON_AddNumberToObject(telemetry, "client_backoff_ms", telemetry_diag.client_backoff_ms);
        cJSON_AddNumberToObject(telemetry, "idle_delay_ms", telemetry_diag.idle_delay_ms);
        cJSON_AddBoolToObject(telemetry, "interval_enabled", telemetry_diag.interval_enabled);
        cJSON_AddBoolToObject(telemetry, "manual_request_pending", telemetry_diag.manual_request_pending);
        cJSON_AddNumberToObject(telemetry, "publish_queue_depth", telemetry_diag.publish_queue_depth);
        cJSON_AddNumberToObject(telemetry, "total_attempts", pipeline_metrics->total_attempts);
        cJSON_AddNumberToObject(telemetry, "total_success", pipeline_metrics->total_success);
        cJSON_AddNumberToObject(telemetry, "total_failure", pipeline_metrics->total_failure);
        cJSON_AddNumberToObject(telemetry, "last_sequence_id", pipeline_metrics->last_sequence_id);
        cJSON_AddNumberToObject(telemetry, "last_sensor_count", pipeline_metrics->last_sensor_count);
        cJSON_AddNumberToObject(telemetry, "last_rssi", pipeline_metrics->last_rssi);
        cJSON_AddBoolToObject(telemetry, "last_battery_valid", pipeline_metrics->last_battery_valid);
        if (pipeline_metrics->last_battery_valid) {
            cJSON_AddNumberToObject(telemetry,
                                    "last_battery_percent",
                                    pipeline_metrics->last_battery_percent);
        }
        cJSON_AddNumberToObject(telemetry,
                                "last_capture_us",
                                (double)pipeline_metrics->last_capture_us);
        cJSON_AddNumberToObject(telemetry,
                                "last_publish_us",
                                (double)pipeline_metrics->last_publish_us);
        if (pipeline_metrics->last_capture_us > 0) {
            double seconds_since_capture = (double)(now_us - pipeline_metrics->last_capture_us) / 1000000.0;
            cJSON_AddNumberToObject(telemetry, "seconds_since_capture", seconds_since_capture);
        } else {
            cJSON_AddNumberToObject(telemetry, "seconds_since_capture", -1);
        }
        if (pipeline_metrics->last_publish_us > 0) {
            double seconds_since_publish = (double)(now_us - pipeline_metrics->last_publish_us) / 1000000.0;
            cJSON_AddNumberToObject(telemetry, "seconds_since_publish", seconds_since_publish);
        } else {
            cJSON_AddNumberToObject(telemetry, "seconds_since_publish", -1);
        }
        double scheduler_last_publish_us =
            (telemetry_diag.scheduler_last_publish_us > 0)
                ? (double)telemetry_diag.scheduler_last_publish_us
                : -1;
        cJSON_AddNumberToObject(telemetry, "scheduler_last_publish_us", scheduler_last_publish_us);
        if (telemetry_diag.scheduler_last_publish_us > 0) {
            double scheduler_delta =
                (double)(now_us - telemetry_diag.scheduler_last_publish_us) / 1000000.0;
            cJSON_AddNumberToObject(telemetry,
                                    "seconds_since_scheduler_publish",
                                    scheduler_delta);
        } else {
            cJSON_AddNumberToObject(telemetry, "seconds_since_scheduler_publish", -1);
        }

        double scheduler_next_retry_us =
            (telemetry_diag.scheduler_next_retry_us > 0)
                ? (double)telemetry_diag.scheduler_next_retry_us
                : -1;
        cJSON_AddNumberToObject(telemetry, "scheduler_next_retry_us", scheduler_next_retry_us);
        if (telemetry_diag.scheduler_next_retry_us > now_us) {
            double until_retry = (double)(telemetry_diag.scheduler_next_retry_us - now_us) / 1000000.0;
            cJSON_AddNumberToObject(telemetry, "seconds_until_next_retry", until_retry);
        } else {
            cJSON_AddNumberToObject(telemetry, "seconds_until_next_retry", -1);
        }
    }

    if (telemetry != NULL) {
        cJSON_AddItemToObject(root, "telemetry", telemetry);
    }

    cJSON *watchdog = cJSON_CreateObject();
    if (watchdog != NULL) {
        cJSON_AddBoolToObject(watchdog, "active", watchdog_metrics.active);
        cJSON_AddBoolToObject(watchdog, "tripped", watchdog_metrics.tripped);
        cJSON_AddNumberToObject(watchdog, "trip_count", watchdog_metrics.trip_count);
        cJSON_AddNumberToObject(watchdog,
                                "poll_interval_ms",
                                watchdog_metrics.poll_interval_ms);
        cJSON_AddNumberToObject(watchdog,
                                "stuck_threshold_ms",
                                watchdog_metrics.stuck_threshold_ms);
        cJSON_AddNumberToObject(watchdog,
                                "report_interval_ms",
                                watchdog_metrics.report_interval_ms);
        if (watchdog_metrics.unhealthy_since_us > 0) {
            double unhealthy_ms =
                (double)(now_us - watchdog_metrics.unhealthy_since_us) / 1000.0;
            cJSON_AddNumberToObject(watchdog, "unhealthy_duration_ms", unhealthy_ms);
        } else {
            cJSON_AddNumberToObject(watchdog, "unhealthy_duration_ms", -1);
        }
        if (watchdog_metrics.last_report_us > 0) {
            double seconds_since_report =
                (double)(now_us - watchdog_metrics.last_report_us) / 1000000.0;
            cJSON_AddNumberToObject(watchdog, "seconds_since_last_report", seconds_since_report);
        } else {
            cJSON_AddNumberToObject(watchdog, "seconds_since_last_report", -1);
        }
    }

    if (watchdog != NULL) {
        cJSON_AddItemToObject(root, "watchdog", watchdog);
    }

    char *json_str = cJSON_PrintUnformatted(root);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, HTTPD_RESP_USE_STRLEN);

    free(json_str);
    cJSON_Delete(root);
    return ESP_OK;
}

/**
 * @brief API clear WiFi endpoint
 */
static esp_err_t api_clear_wifi_handler(httpd_req_t *req)
{
    ESP_LOGW(TAG, "WiFi clear requested via dashboard");
    
    // Clear WiFi credentials via provisioning package
    esp_err_t ret = provisioning_clear_saved_network();
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to clear WiFi credentials: %s", esp_err_to_name(ret));
        httpd_resp_set_type(req, "application/json");
        httpd_resp_send(req, "{\"status\":\"error\"}", HTTPD_RESP_USE_STRLEN);
        return ESP_FAIL;
    }
    
    // Send response
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"status\":\"success\"}", HTTPD_RESP_USE_STRLEN);
    
    // Restart device after a delay
    vTaskDelay(pdMS_TO_TICKS(1000));
    esp_restart();
    
    return ESP_OK;
}

/**
 * @brief API reboot endpoint
 */
static esp_err_t api_reboot_handler(httpd_req_t *req)
{
    ESP_LOGW(TAG, "Reboot requested via dashboard");
    
    // Send response
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"status\":\"rebooting\"}", HTTPD_RESP_USE_STRLEN);
    
    // Restart device after a delay
    vTaskDelay(pdMS_TO_TICKS(1000));
    esp_restart();
    
    return ESP_OK;
}

/**
 * @brief API test MQTT endpoint
 */
static esp_err_t api_test_mqtt_handler(httpd_req_t *req)
{
    ESP_LOGI(TAG, "MQTT connection test requested");

    mqtt_connection_metrics_t metrics = {0};
    mqtt_connection_controller_get_metrics(&metrics);

    cJSON *root = cJSON_CreateObject();
    cJSON_AddStringToObject(root, "status", "tested");
    cJSON_AddBoolToObject(root, "connected", metrics.state == MQTT_STATE_CONNECTED);
    cJSON_AddStringToObject(root, "state", mqtt_state_to_string(metrics.state));
    cJSON_AddNumberToObject(root, "state_code", metrics.state);

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, HTTPD_RESP_USE_STRLEN);
    free(json_str);

    return ESP_OK;
}

/**
 * @brief API settings endpoint
 */
static esp_err_t api_settings_handler(httpd_req_t *req)
{
    // Handle GET request - return current settings
    if (req->method == HTTP_GET) {
        cJSON *root = cJSON_CreateObject();
        
        // Get current MQTT telemetry interval
        uint32_t mqtt_interval = mqtt_get_telemetry_interval();
        cJSON_AddNumberToObject(root, "mqtt_interval", mqtt_interval);
        
        // Get sensor reading interval
        uint32_t sensor_interval = sensor_manager_get_reading_interval();
        cJSON_AddNumberToObject(root, "sensor_interval", sensor_interval);
        
        char *json_str = cJSON_PrintUnformatted(root);
        cJSON_Delete(root);
        
        httpd_resp_set_type(req, "application/json");
        httpd_resp_sendstr(req, json_str);
        free(json_str);
        
        return ESP_OK;
    }
    
    // Handle POST request - update settings
    char content[200];
    int ret = httpd_req_recv(req, content, sizeof(content) - 1);
    if (ret <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid request");
        return ESP_FAIL;
    }
    content[ret] = '\0';
    
    // Parse JSON
    cJSON *root = cJSON_Parse(content);
    if (root == NULL) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid JSON");
        return ESP_FAIL;
    }
    
    // Update MQTT telemetry interval if present
    cJSON *mqtt_interval = cJSON_GetObjectItem(root, "mqtt_interval");
    if (mqtt_interval != NULL && cJSON_IsNumber(mqtt_interval)) {
        int interval_val = mqtt_interval->valueint;
        if (interval_val < 0) {
            cJSON_Delete(root);
            httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Interval must be >= 0");
            return ESP_FAIL;
        }
        
        ESP_LOGI(TAG, "Setting MQTT telemetry interval to %d seconds (0=on-read only)", interval_val);
        esp_err_t err = mqtt_set_telemetry_interval(interval_val);
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "Failed to set MQTT interval: %s", esp_err_to_name(err));
        }
    }
    
    // Update sensor reading interval if present
    cJSON *sensor_interval = cJSON_GetObjectItem(root, "sensor_interval");
    if (sensor_interval != NULL && cJSON_IsNumber(sensor_interval)) {
        int interval_val = sensor_interval->valueint;
        if (interval_val < 1) {
            cJSON_Delete(root);
            httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Sensor interval must be >= 1");
            return ESP_FAIL;
        }
        
        ESP_LOGI(TAG, "Setting sensor reading interval to %d seconds", interval_val);
        sensor_manager_set_reading_interval(interval_val);
    }
    
    cJSON_Delete(root);
    
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"status\":\"saved\"}", HTTPD_RESP_USE_STRLEN);
    
    return ESP_OK;
}

/**
 * @brief POST /api/settings/reset - Reset settings to defaults
 */
static esp_err_t api_settings_reset_handler(httpd_req_t *req)
{
    const uint32_t DEFAULT_MQTT_INTERVAL = 10;
    const uint32_t DEFAULT_SENSOR_INTERVAL = 10;
    
    ESP_LOGI(TAG, "Resetting settings to defaults");
    
    // Reset MQTT interval
    mqtt_set_telemetry_interval(DEFAULT_MQTT_INTERVAL);
    
    // Reset sensor interval
    sensor_manager_set_reading_interval(DEFAULT_SENSOR_INTERVAL);
    
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"reset\",\"mqtt_interval\":10,\"sensor_interval\":10}");
    
    return ESP_OK;
}

/**
 * @brief POST /api/sensors/pause - Pause sensor reading task
 */

// URI handlers
static const httpd_uri_t favicon_uri = {
    .uri = "/favicon.ico",
    .method = HTTP_GET,
    .handler = favicon_handler,
    .user_ctx = NULL
};

static const httpd_uri_t root_uri = {
    .uri = "/",
    .method = HTTP_GET,
    .handler = root_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_status_uri = {
    .uri = "/api/status",
    .method = HTTP_GET,
    .handler = api_status_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_logs_uri = {
    .uri = "/api/logs",
    .method = HTTP_GET,
    .handler = api_logs_handler,
    .user_ctx = NULL
};

#if CONFIG_KC_SD_LOGGER_ENABLED
static const httpd_uri_t api_logs_download_uri = {
    .uri = "/api/logs/download",
    .method = HTTP_GET,
    .handler = api_logs_download_handler,
    .user_ctx = NULL
};
#endif

static const httpd_uri_t api_mqtt_status_uri = {
    .uri = "/api/mqtt/status",
    .method = HTTP_GET,
    .handler = api_mqtt_status_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_clear_wifi_uri = {
    .uri = "/api/clear-wifi",
    .method = HTTP_POST,
    .handler = api_clear_wifi_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_reboot_uri = {
    .uri = "/api/reboot",
    .method = HTTP_POST,
    .handler = api_reboot_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_test_mqtt_uri = {
    .uri = "/api/test-mqtt",
    .method = HTTP_POST,
    .handler = api_test_mqtt_handler,
    .user_ctx = NULL
};

// Settings API - handles both GET and POST
static const httpd_uri_t api_settings_get_uri = {
    .uri = "/api/settings",
    .method = HTTP_GET,
    .handler = api_settings_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_settings_post_uri = {
    .uri = "/api/settings",
    .method = HTTP_POST,
    .handler = api_settings_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_settings_reset_uri = {
    .uri = "/api/settings/reset",
    .method = HTTP_POST,
    .handler = api_settings_reset_handler,
    .user_ctx = NULL
};

/**
 * @brief List web files API handler
 */
static esp_err_t api_webfiles_list_handler(httpd_req_t *req)
{
    char *json = NULL;
    if (web_editor_list_files(&json) == ESP_OK) {
        httpd_resp_set_type(req, "application/json");
        httpd_resp_send(req, json, HTTPD_RESP_USE_STRLEN);
        free(json);
        return ESP_OK;
    }
    httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to list files");
    return ESP_FAIL;
}

/**
 * @brief Get web file content API handler
 */
static esp_err_t api_webfiles_get_handler(httpd_req_t *req)
{
    // Extract filename from URI (e.g., /api/webfiles/index.html)
    const char *filename = req->uri + strlen("/api/webfiles/");
    
    ESP_LOGI(TAG, "GET handler called for file: %s", filename);
    
    char *content = NULL;
    size_t size = 0;
    esp_err_t ret = web_editor_load_file(filename, &content, &size);
    
    if (ret == ESP_OK) {
        httpd_resp_set_type(req, web_editor_get_content_type(filename));
        httpd_resp_send(req, content, size);
        free(content);
        return ESP_OK;
    }
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "File not found");
    return ESP_FAIL;
}

/**
 * @brief Save web file content API handler
 */
static esp_err_t api_webfiles_put_handler(httpd_req_t *req)
{
    // Extract filename from URI (e.g., /api/webfiles/index.html)
    const char *filename = req->uri + strlen("/api/webfiles/");
    
    // Read request body (allocate from PSRAM first to avoid IRAM fragmentation)
    char *content = heap_caps_malloc(WEB_EDITOR_MAX_FILE_SIZE, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (content == NULL) {
        content = malloc(WEB_EDITOR_MAX_FILE_SIZE);
    }
    if (content == NULL) {
        ESP_LOGE(TAG, "webfiles PUT: failed to allocate %d bytes", WEB_EDITOR_MAX_FILE_SIZE);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Out of memory");
        return ESP_FAIL;
    }
    
    int total_len = 0;
    int received;
    while (total_len < req->content_len && total_len < WEB_EDITOR_MAX_FILE_SIZE) {
        size_t bytes_to_read = req->content_len - total_len;
        if (bytes_to_read > WEB_EDITOR_MAX_FILE_SIZE - total_len) {
            bytes_to_read = WEB_EDITOR_MAX_FILE_SIZE - total_len;
        }
        received = httpd_req_recv(req, content + total_len, bytes_to_read);
        if (received <= 0) {
            free(content);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to read request");
            return ESP_FAIL;
        }
        total_len += received;
    }
    
    if (total_len == WEB_EDITOR_MAX_FILE_SIZE && total_len < req->content_len) {
        free(content);
        httpd_resp_send_err(req, HTTPD_413_CONTENT_TOO_LARGE, "File exceeds 200KB limit");
        return ESP_FAIL;
    }
    
    // Persist to on-device filesystem
    esp_err_t ret = web_editor_save_file(filename, content, total_len);
    free(content);
    
    if (ret == ESP_OK) {
        httpd_resp_set_type(req, "application/json");
        httpd_resp_sendstr(req, "{\"success\":true}");
        return ESP_OK;
    }
    httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to save file");
    return ESP_FAIL;
}

static esp_err_t api_webfiles_reset_handler(httpd_req_t *req)
{
    esp_err_t err = web_editor_reset_fs();
    if (err == ESP_OK) {
        httpd_resp_set_type(req, "application/json");
        httpd_resp_sendstr(req, "{\"success\":true,\"message\":\"filesystem reset\"}");
        return ESP_OK;
    }

    char msg[80];
    snprintf(msg, sizeof(msg), "Reset failed (%s)", esp_err_to_name(err));
    httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, msg);
    return ESP_FAIL;
}

static const httpd_uri_t api_webfiles_list_uri = {
    .uri = "/api/webfiles/list",
    .method = HTTP_GET,
    .handler = api_webfiles_list_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_webfiles_get_uri = {
    .uri = "/api/webfiles/*",
    .method = HTTP_GET,
    .handler = api_webfiles_get_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_webfiles_put_uri = {
    .uri = "/api/webfiles/*",
    .method = HTTP_PUT,
    .handler = api_webfiles_put_handler,
    .user_ctx = NULL
};

static const httpd_uri_t api_webfiles_reset_uri = {
    .uri = "/api/webfiles/reset",
    .method = HTTP_POST,
    .handler = api_webfiles_reset_handler,
    .user_ctx = NULL
};

static void ota_reboot_task(void *arg)
{
    vTaskDelay(pdMS_TO_TICKS(1500));
    esp_restart();
}

static void schedule_ota_reboot(void)
{
    BaseType_t created = xTaskCreate(ota_reboot_task, "ota_reboot", 2048, NULL, 5, NULL);
    if (created != pdPASS) {
        ESP_LOGE(TAG, "Failed to create OTA reboot task");
    }
}

static esp_err_t api_firmware_upload_handler(httpd_req_t *req)
{
    if (req->content_len <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "No firmware provided");
        return ESP_FAIL;
    }

    const esp_partition_t *update_partition = esp_ota_get_next_update_partition(NULL);
    if (update_partition == NULL) {
        ESP_LOGE(TAG, "No OTA partition available");
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OTA partition missing");
        return ESP_FAIL;
    }

    if (req->content_len > update_partition->size) {
        ESP_LOGW(TAG, "Firmware image too large: %d (max %d)", req->content_len, update_partition->size);
        httpd_resp_send_err(req, HTTPD_413_CONTENT_TOO_LARGE, "Firmware image too large");
        return ESP_FAIL;
    }

    esp_ota_handle_t ota_handle = 0;
    esp_err_t err = esp_ota_begin(update_partition, req->content_len, &ota_handle);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_ota_begin failed: %s", esp_err_to_name(err));
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to start OTA");
        return ESP_FAIL;
    }

    uint8_t *ota_buffer = heap_caps_malloc(OTA_UPLOAD_BUFFER_SIZE, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (ota_buffer == NULL) {
        ota_buffer = malloc(OTA_UPLOAD_BUFFER_SIZE);
    }
    if (ota_buffer == NULL) {
        ESP_LOGE(TAG, "Failed to allocate OTA buffer");
        esp_ota_abort(ota_handle);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Out of memory");
        return ESP_FAIL;
    }

    int remaining = req->content_len;
    while (remaining > 0) {
        int chunk = remaining > OTA_UPLOAD_BUFFER_SIZE ? OTA_UPLOAD_BUFFER_SIZE : remaining;
        int received = httpd_req_recv(req, (char *)ota_buffer, chunk);
        if (received <= 0) {
            if (received == HTTPD_SOCK_ERR_TIMEOUT) {
                continue;
            }
            ESP_LOGE(TAG, "OTA upload interrupted (%d)", received);
            free(ota_buffer);
            esp_ota_abort(ota_handle);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Upload interrupted");
            return ESP_FAIL;
        }

        err = esp_ota_write(ota_handle, ota_buffer, received);
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "esp_ota_write failed: %s", esp_err_to_name(err));
            free(ota_buffer);
            esp_ota_abort(ota_handle);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Flash write failed");
            return ESP_FAIL;
        }
        remaining -= received;
    }

    free(ota_buffer);

    err = esp_ota_end(ota_handle);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_ota_end failed: %s", esp_err_to_name(err));
        esp_ota_abort(ota_handle);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OTA finalize failed");
        return ESP_FAIL;
    }

    err = esp_ota_set_boot_partition(update_partition);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to set boot partition: %s", esp_err_to_name(err));
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to set boot partition");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "Firmware uploaded successfully (%d bytes)", req->content_len);

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"uploaded\",\"reboot\":true}");

    schedule_ota_reboot();
    return ESP_OK;
}

static const httpd_uri_t api_firmware_upload_uri = {
    .uri = "/api/firmware/upload",
    .method = HTTP_POST,
    .handler = api_firmware_upload_handler,
    .user_ctx = NULL
};

/**
 * @brief Handler for CA certificate download
 */
static esp_err_t ca_cert_handler(httpd_req_t *req)
{
    nvs_handle_t nvs_handle;
    esp_err_t err = nvs_open_from_partition("https", "https", NVS_READONLY, &nvs_handle);
    if (err != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "CA certificate not found");
        return ESP_FAIL;
    }
    
    size_t ca_cert_len = 0;
    err = nvs_get_str(nvs_handle, "ca_cert", NULL, &ca_cert_len);
    if (err != ESP_OK || ca_cert_len == 0) {
        nvs_close(nvs_handle);
        httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "CA certificate not available");
        return ESP_FAIL;
    }
    
    char *ca_cert = malloc(ca_cert_len);
    if (ca_cert == NULL) {
        nvs_close(nvs_handle);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Out of memory");
        return ESP_FAIL;
    }
    
    err = nvs_get_str(nvs_handle, "ca_cert", ca_cert, &ca_cert_len);
    nvs_close(nvs_handle);
    
    if (err != ESP_OK) {
        free(ca_cert);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Failed to read CA certificate");
        return ESP_FAIL;
    }
    
    // Set content type and disposition for download
    httpd_resp_set_type(req, "application/x-pem-file");
    httpd_resp_set_hdr(req, "Content-Disposition", "attachment; filename=\"kannacloud-ca.crt\"");
    
    httpd_resp_send(req, ca_cert, ca_cert_len - 1);
    free(ca_cert);
    
    return ESP_OK;
}

static const httpd_uri_t ca_cert_uri = {
    .uri = "/ca.crt",
    .method = HTTP_GET,
    .handler = ca_cert_handler,
    .user_ctx = NULL
};

esp_err_t http_server_start(const http_server_config_t *config)
{
    if (config == NULL) {
        ESP_LOGE(TAG, "HTTPS server configuration missing parameters");
        return ESP_ERR_INVALID_ARG;
    }

    if (s_server != NULL) {
        ESP_LOGW(TAG, "HTTPS server already running");
        return ESP_OK;
    }

    s_http_config = *config;

    // Ensure any TLS material from a previous attempt is cleared
    http_server_free_tls_assets();
    
    // Initialize FATFS-backed dashboard storage
    web_editor_init_fs();
    
    ESP_LOGI(TAG, "Starting HTTPS server...");
    
    // Get certificates from cloud provisioning
    s_https_certificate = malloc(SERVICES_TLS_CERT_MAX_BYTES);
    s_https_private_key = malloc(SERVICES_TLS_KEY_MAX_BYTES);
    
    if (s_https_certificate == NULL || s_https_private_key == NULL) {
        ESP_LOGE(TAG, "Failed to allocate memory for certificates");
        http_server_free_tls_assets();
        return ESP_ERR_NO_MEM;
    }
    
    size_t cert_len = 0;
    size_t key_len = 0;
    esp_err_t err = services_provisioning_load_https_certificate(s_https_certificate, &cert_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to get certificate: %s", esp_err_to_name(err));
        http_server_free_tls_assets();
        return err;
    }
    
    err = services_provisioning_load_https_private_key(s_https_private_key, &key_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to get private key: %s", esp_err_to_name(err));
        http_server_free_tls_assets();
        return err;
    }
    
    s_https_certificate_len = cert_len;
    s_https_private_key_len = key_len;

    ESP_LOGI(TAG, "Certificate length: %zu bytes", cert_len);
    ESP_LOGI(TAG, "Private key length: %zu bytes", key_len);
    
    // Debug certificate format
    ESP_LOGI(TAG, "Cert first 100 chars: %.100s", s_https_certificate);
    if (cert_len > 100) {
        ESP_LOGI(TAG, "Cert last 100 chars: %s", s_https_certificate + cert_len - 100);
    }
    
    // Configure HTTPS server
    httpd_ssl_config_t ssl_cfg = HTTPD_SSL_CONFIG_DEFAULT();
    ssl_cfg.httpd.max_uri_handlers = 50;  // Increased for web file editor + sensor action endpoints + new diagnostic endpoints
    ssl_cfg.httpd.stack_size = 8192;  // Reduced stack to save memory
    ssl_cfg.httpd.max_open_sockets = 3;  // Allow multiple connections now that PSRAM is enabled
    ssl_cfg.httpd.lru_purge_enable = true;  // Enable automatic cleanup of old connections
    ssl_cfg.httpd.close_fn = NULL;  // Use default close function
    ssl_cfg.httpd.recv_wait_timeout = 30;  // Increased timeout for SSL handshake (was 10)
    ssl_cfg.httpd.send_wait_timeout = 30;  // Increased timeout for SSL handshake (was 10)
    ssl_cfg.port_insecure = 0;  // Disable insecure port (HTTPS only)
    ssl_cfg.httpd.uri_match_fn = httpd_uri_match_wildcard;  // Enable wildcard URI matching
    ssl_cfg.httpd.server_port = s_http_config.https_port;
    
    // Set certificates (PEM format from NVS is already null-terminated)
    // mbedTLS needs length + 1 to include the null terminator
    ssl_cfg.servercert = (const uint8_t *)s_https_certificate;
    ssl_cfg.servercert_len = s_https_certificate_len + 1;
    ssl_cfg.prvtkey_pem = (const uint8_t *)s_https_private_key;
    ssl_cfg.prvtkey_len = s_https_private_key_len + 1;
    
    // Skip client certificate verification (allows browsers to connect without trusting cert)
    ssl_cfg.session_tickets = false;  // Disable session resumption for testing
    ssl_cfg.use_secure_element = false;  // Not using hardware secure element
    
    // Start server
    err = httpd_ssl_start(&s_server, &ssl_cfg);
    
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start HTTPS server: %s", esp_err_to_name(err));
        http_server_free_tls_assets();
        return err;
    }
    
    // Register URI handlers
    httpd_register_uri_handler(s_server, &favicon_uri);
    httpd_register_uri_handler(s_server, &root_uri);
    httpd_register_uri_handler(s_server, &ca_cert_uri);  // CA certificate download
    httpd_register_uri_handler(s_server, &api_status_uri);
    httpd_register_uri_handler(s_server, &api_logs_uri);
#if CONFIG_KC_SD_LOGGER_ENABLED
    httpd_register_uri_handler(s_server, &api_logs_download_uri);
#endif
    httpd_register_uri_handler(s_server, &api_mqtt_status_uri);
    httpd_register_uri_handler(s_server, &api_clear_wifi_uri);
    httpd_register_uri_handler(s_server, &api_reboot_uri);
    httpd_register_uri_handler(s_server, &api_test_mqtt_uri);
    httpd_register_uri_handler(s_server, &api_settings_get_uri);
    httpd_register_uri_handler(s_server, &api_settings_post_uri);
    httpd_register_uri_handler(s_server, &api_settings_reset_uri);
    httpd_register_uri_handler(s_server, &api_webfiles_list_uri);
    httpd_register_uri_handler(s_server, &api_webfiles_reset_uri);
    httpd_register_uri_handler(s_server, &api_webfiles_get_uri);
    httpd_register_uri_handler(s_server, &api_webfiles_put_uri);
    httpd_register_uri_handler(s_server, &api_firmware_upload_uri);

    if (http_handlers_sensors_init(s_server) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to register sensor HTTP endpoints");
    }

    esp_err_t ws_err = http_websocket_init(s_server);
    if (ws_err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to initialize WebSocket endpoint: %s", esp_err_to_name(ws_err));
    } else {
        esp_err_t listener_err = sensor_pipeline_register_snapshot_listener(
            NULL,
            http_websocket_snapshot_handler,
            NULL);
        if (listener_err != ESP_OK) {
            ESP_LOGE(TAG, "Failed to register sensor snapshot listener: %s", esp_err_to_name(listener_err));
            http_websocket_deinit();
        }
    }

    ESP_LOGI(TAG, "Registered sensor + dashboard API endpoints");
    
    return ESP_OK;
}

esp_err_t http_server_stop(void)
{
    if (s_server == NULL) {
        return ESP_OK;
    }
    
    http_websocket_deinit();
    sensor_pipeline_register_snapshot_listener(NULL, NULL, NULL);

    ESP_LOGI(TAG, "Stopping HTTPS server");
    httpd_ssl_stop(s_server);
    s_server = NULL;
    http_server_free_tls_assets();
    
    return ESP_OK;
}

bool http_server_is_running(void)
{
    return (s_server != NULL);
}

#else
// ESP32-C6: Stub implementations (no local dashboard)

esp_err_t http_server_start(const http_server_config_t *config)
{
    (void)config;
    ESP_LOGW(TAG, "HTTP server not available on ESP32-C6 (cloud-only mode)");
    return ESP_ERR_NOT_SUPPORTED;
}

esp_err_t http_server_stop(void)
{
    return ESP_OK;
}

bool http_server_is_running(void)
{
    return false;
}

#endif // CONFIG_IDF_TARGET_ESP32C6
