#!/usr/bin/env python3
"""Generate a header with SHA256 digests for runtime JSON blobs."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys
from typing import Tuple


def _read_bytes(path: pathlib.Path) -> bytes:
    try:
        return path.read_bytes()
    except FileNotFoundError as exc:
        raise SystemExit(f"Missing runtime config file: {path}") from exc


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _emit_header(output: pathlib.Path, services: Tuple[str, int], api_keys: Tuple[str, int]) -> None:
    services_hash, services_size = services
    api_hash, api_size = api_keys

    header = f"""// Auto-generated by tools/generate_runtime_config_hash.py
// Do not edit manually.
#pragma once

#define RUNTIME_CONFIG_SERVICES_SHA256 "{services_hash}"
#define RUNTIME_CONFIG_SERVICES_SIZE_BYTES {services_size}u
#define RUNTIME_CONFIG_API_KEYS_SHA256 "{api_hash}"
#define RUNTIME_CONFIG_API_KEYS_SIZE_BYTES {api_size}u
"""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Emit runtime_config_hash.h containing SHA256 digests")
    parser.add_argument("--services", required=True, help="Path to config/runtime/services.json")
    parser.add_argument("--keys", required=True, help="Path to config/runtime/api_keys.json")
    parser.add_argument("--output", required=True, help="Header file to generate")
    args = parser.parse_args()

    services_path = pathlib.Path(args.services).resolve()
    keys_path = pathlib.Path(args.keys).resolve()
    output_path = pathlib.Path(args.output)

    services_bytes = _read_bytes(services_path)
    keys_bytes = _read_bytes(keys_path)

    _emit_header(
        output_path,
        ( _digest(services_bytes), len(services_bytes) ),
        ( _digest(keys_bytes), len(keys_bytes) ),
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
